In [ ]:
import pandas as pd

Объект Series являтся одномерным набором данных. Он создается из обычного массива, дополнительно вы можете указать индексы для значений

In [ ]:
my_series=pd.Series([1,2,5,8,1,7,3,1,2,45

],index=["a","b","c","d","e","f","g","h","j","k"])

In [ ]:
my_series

a     1
b     2
c     5
d     8
e     1
f     7
g     3
h     1
j     2
k    45
dtype: int64

Главной особенностью объектов Series и Dataframe является возможность фильтровать их. Мы можем написать любое логическое условие и оно будет применено ко всем элементам.

В качестве ответа мы получаем информацию о том выполняется условие, или нет

In [ ]:
my_series>4

a    False
b    False
c     True
d     True
e    False
f     True
g    False
h    False
j    False
k     True
dtype: bool

И это позволяет нам фильтровать элементы. Тут мы получим только те элементы, которые больше 4

In [ ]:
my_series[my_series>4]

Так-же мы можем применять операции/функции ко всем элементам в Series.

В данном примере мы получаем все элементы, которые больше 4 и перезаписываем их. В них теперь хранятся их значения, умноженные на 3

In [ ]:
my_series[my_series>4]=my_series[my_series>4]*3

Что бы получить элемент Series мы используем его индекс

In [ ]:
my_series['a']

np.int64(2)

Таким образом создается DataFrame. В качестве данных, которые формируют его, используется словарь, а не обычный массив.
Точно так-же вы можете указать индексы рядов

In [ ]:
data=pd.DataFrame({
    'contry':["Russia","Kazakhstan","Belarus"],
    'population':[144,17,9.5],
    'capital':["Moscow","Astana","Minsk"]

}
,index=["RU","RZ","BY"]

)

Важно понимать, что отдельные ряды/столбцы, которые вы можете получать из DataFrame являются объектами Series и вы можете работать с ними (фильтровать, менять и т.д)

In [ ]:
data

        contry  population capital
RU      Russia       144.0  Moscow
RZ  Kazakhstan        17.0  Astana
BY     Belarus         9.5   Minsk

Вы можете получить весь столбец обратившись к его заголовку.

In [ ]:
data["contry"]

Вы можете получить ряд по его индексу

In [ ]:
data.loc["RU"]

contry        Russia
population     144.0
capital       Moscow
Name: RU, dtype: object

Либо по его номеру

In [ ]:
data.iloc[1]

contry        Kazakhstan
population          17.0
capital           Astana
Name: RZ, dtype: object

Dataframe имеют множество параметров, один из них - index, он содержит список всех индексов в таблице

In [ ]:
data.index

Index(['RU', 'RZ', 'BY'], dtype='object')

Вы моежете получить несколько рядов/столбцов, если укажите не одно значение, а массив значений

In [ ]:
data.loc[["RU","RZ"]]

        contry  population capital
RU      Russia       144.0  Moscow
RZ  Kazakhstan        17.0  Astana

Вы можете получать конкретные ряды и конкретные столбцы

In [ ]:
data.loc[["RU","RZ"],"capital"]

RU    Moscow
RZ    Astana
Name: capital, dtype: object

Вы можете создать новый столбец, если зададите значение столбцу, которого нет в таблице. Количество значений должно соответствовать количеству рядов в таблице

In [ ]:
data["size"]=[17,2.7,0.2]

In [ ]:
data

        contry  population capital  size  population_per_million
RU      Russia       144.0  Moscow  17.0               12.000000
RZ  Kazakhstan        17.0  Astana   2.7                1.416667
BY     Belarus         9.5   Minsk   0.2                0.791667

Вы можете выполнять операции между столбцами

In [ ]:
data["population_per_million"]=data.population/data.size

Функция drop удаляет столбец, либо ряд.

По умолчанию она ищет ряд с указанным рядом и удаляет его. Если стоит параметр axis="columns", то функция удаляет столбец.

По умолчанию функция не применяет изменения, а возвращяет измененную таблицу, если вы хотите внести изменения в оригинал, то поставьте параметр inplace=True

In [ ]:
data.drop(["population_per_million"],axis="columns",inplace=True)

In [ ]:
data

        contry  population capital
RU      Russia       144.0  Moscow
RZ  Kazakhstan        17.0  Astana
BY     Belarus         9.5   Minsk

In [ ]:
data.drop(["BY"],inplace=True)

In [ ]:
data

     contry  population capital  size
RU   Russia       144.0  Moscow  17.0
BY  Belarus         9.5   Minsk   0.2

Вы можете фильтровать данные в столбцах/ряда, точно так-же как вы делаете с сериями

In [ ]:
data[data.population>10].population

RU    144.0
Name: population, dtype: float64

In [ ]:
data['contry']

RU     Russia
BY    Belarus
Name: contry, dtype: object

Работы с таблицей DataFrame

In [ ]:
import pandas as pd

# ==========================
# ШАГ 1. Создаем таблицу
# ==========================
data = {
    'Товар': ['Смартфон', 'Наушники', 'Ноутбук', 'Чехол',
              'Планшет', 'Колонка', 'Мышка', 'Клавиатура'],
    'Категория': ['Телефоны', 'Аудио', 'Компьютеры', 'Аксессуары',
                  'Компьютеры', 'Аудио', 'Аксессуары', 'Аксессуары'],
    'Цена': [45000, 3500, 80000, 1500, 30000, 7000, 2000, 4500],
    'Количество': [2, 10, 1, 25, 3, 6, 15, 8]
}

orders = pd.DataFrame(data)

# ==========================
# ШАГ 2. Смотрим первые строки
# ==========================
print("--- Первые 4 строки ---")
print(orders.head(4))

# ==========================
# ШАГ 3. Создаем столбец "Сумма_заказа"
# ==========================
orders['Сумма_заказа'] = orders['Цена'] * orders['Количество']
print("\n--- Таблица с новым столбцом ---")
print(orders)

# ==========================
# ШАГ 4. Фильтр по категории "Аудио"
# ==========================
print("\n--- Товары категории 'Аудио' ---")
audio_products = orders[orders['Категория'] == 'Аудио']
print(audio_products)

# ==========================
# ШАГ 5. Фильтр по цене > 5000
# ==========================
print("\n--- Товары дороже 5000 руб. ---")
expensive_products = orders[orders['Цена'] > 5000]
print(expensive_products)

# ==========================
# ШАГ 6. Считаем статистику
# ==========================
total_revenue = orders['Сумма_заказа'].sum()
avg_price = orders['Цена'].mean()
max_order = orders['Сумма_заказа'].max()

print("\n--- Отчет для руководителя ---")
print(f"Общая выручка магазина: {total_revenue} руб.")
print(f"Средняя цена товара: {avg_price} руб.")
print(f"Максимальная сумма одного заказа: {max_order} руб.")

# ==========================
# ШАГ 7. Бонус: общая статистика
# ==========================
print("\n--- Сводная статистика по числовым столбцам ---")
print(orders.describe())